spring:
  profiles:
    active: prod
  redis:
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: false